# -*- coding: utf-8 -*-
"""Airbnb Project_Finsihed Work_Airbnb_Preprocessing (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWWgR88j3nYRwDtCnDUsFg8ziiHbu54M

# Airbnb PreProcessing

## Setup and Data Loading
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %pip install --quiet seaborn
import seaborn as sns
from datetime import datetime
import re
import json
import ast
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import warnings
warnings.filterwarnings('ignore')

# Display Options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)

# Commented out IPython magic to ensure Python compatibility.
# %pip install --quiet transformers torch torchvision requests Pillow scikit-learn

import torch
import torchvision.models as models
import torchvision.transforms as transforms
from transformers import DistilBertTokenizer, DistilBertModel
from PIL import Image
import requests as req
from io import BytesIO
from sklearn.decomposition import PCA
import joblib

# Loading the Dataset
listing_data = pd.read_csv('listings.csv')

listing_data.head

# Select only the specified columns
selected_columns = [
    'name', 'description', 'picture_url', 'property_type', 'room_type',
    'accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities', 'price',
    'number_of_reviews', 'review_scores_rating', 'review_scores_cleanliness',
    'review_scores_location', 'host_since', 'host_response_time', 'host_is_superhost',
    'host_total_listings_count', 'host_identity_verified', 'neighbourhood_group_cleansed',
    'review_scores_accuracy', 'review_scores_checkin', 'review_scores_communication',
    'review_scores_value', 'latitude', 'longitude', 'last_scraped'
]

# Filter to only keep columns that exist in the dataset
existing_columns = [col for col in selected_columns if col in listing_data.columns]
missing_columns = [col for col in selected_columns if col not in listing_data.columns]

# Keep only selected columns
listing_data = listing_data[existing_columns]

"""## Intial Data Exploration"""

# Dataset Info
listing_data.info()

# Check for completely empty columns first
completely_empty = listing_data.columns[listing_data.isnull().all()].tolist()
print(f"Completely empty columns: {completely_empty}")

# Missing Values Analysis
missing_data = listing_data.isnull().sum().sort_values(ascending=False)
missing_pct = (missing_data / len(listing_data)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_data,
    'Missing Percentage': missing_pct
}).round(2)
print(missing_df[missing_df['Missing Count'] > 0])

# Data Types Summary
print(listing_data.dtypes.value_counts())

listing_data["neighbourhood_group_cleansed"].unique()

"""## Data Cleaning

### Missing Values and looking at columns
"""

# Looking at amenities
sample_amenities = listing_data['amenities'].dropna().head(3)

print("Sample 1:", sample_amenities.iloc[0])
print("Sample 2:", sample_amenities.iloc[1])
print("Sample 3:", sample_amenities.iloc[2])

"""### Clean Price and Percentage Columns"""

def clean_price(price_str):
    """Clean price column by removing $ and commas and convert to numeric"""
    if pd.isna(price_str):
        return np.nan
    # Handle different price formats
    price_clean = str(price_str).replace('$', '').replace(',', '').strip()
    if price_clean == '' or price_clean.lower() == 'n/a':
        return np.nan
    return float(price_clean)

def clean_percentage(pct_str):
    """Clean percentage columns by removing % and convert to numeric"""
    if pd.isna(pct_str) or str(pct_str).lower() == 'n/a':
        return np.nan
    pct_clean = str(pct_str).replace('%', '').strip()
    if pct_clean == '':
        return np.nan
    return float(pct_clean)

# Apply price cleaning
if 'price' in listing_data.columns:
    listing_data['price'] = listing_data['price'].apply(clean_price)

# Apply percentage cleaning
percentage_cols = ['host_response_rate', 'host_acceptance_rate']
for col in percentage_cols:
    if col in listing_data.columns:
        listing_data[col] = listing_data[col].apply(clean_percentage)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Handle Boolean Columns"""

boolean_columns = [
    'host_is_superhost', 'host_identity_verified'
]

for col in boolean_columns:
    if col in listing_data.columns:

        # Handle various boolean representations
        listing_data[col] = listing_data[col].map({
            't': True, 'f': False,
            'true': True, 'false': False,
            'TRUE': True, 'FALSE': False,
            True: True, False: False,
            1: True, 0: False,
            '1': True, '0': False
        })

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### More missingness"""

# Examine columns with missingness
moderate_missing = []

for col in missing_df.index:
    missing_percent = missing_df.loc[col, 'Missing Percentage']

    if missing_percent > 10 and missing_percent <= 50:
        moderate_missing.append(col)

print("Columns with 10–50% missing data:", moderate_missing)

# Handle Missing Values in Important Columns
# Fill missing numeric values with median
numeric_fill_cols = ['bathrooms', 'bedrooms', 'beds']
for col in numeric_fill_cols:
    if col in listing_data.columns:
        missing_count = listing_data[col].isnull().sum()
        if missing_count > 0:
            median_val = listing_data[col].median()
            listing_data[col] = listing_data[col].fillna(median_val)

# Fill categorical missing values with appropriate defaults
categorical_fills = {
    'host_response_time': 'unknown',
}

for col, fill_value in categorical_fills.items():
    if col in listing_data.columns:
        missing_count = listing_data[col].isnull().sum()
        if missing_count > 0:
            listing_data[col] = listing_data[col].fillna(fill_value)

# Fill boolean columns with False for missing values
for col in boolean_columns:
    if col in listing_data.columns:
        missing_count = listing_data[col].isnull().sum()
        if missing_count > 0:
            listing_data[col] = listing_data[col].fillna(False)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Data Processing"""

date_columns = [
    'host_since'
]
for col in date_columns:
    if col in listing_data.columns:
        listing_data[col] = pd.to_datetime(listing_data[col], errors='coerce')

"""## Feature Engineering"""

if 'host_since' in listing_data.columns:

    # Converts date time
    listing_data['host_since'] = pd.to_datetime(listing_data['host_since'], errors='coerce')
    listing_data['last_scraped'] = pd.to_datetime(listing_data['last_scraped'], errors='coerce')

    # Computes and converts
    listing_data['host_days_active'] = (listing_data['last_scraped'] - listing_data['host_since']).dt.days
    listing_data.loc[listing_data['host_days_active'] < 0, 'host_days_active'] = None
    listing_data['host_years_active'] = listing_data['host_days_active'] / 365.25

    yrs = listing_data['host_years_active'].dropna()

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

# Review recency
if 'last_review' in listing_data.columns and 'last_scraped' in listing_data.columns:

    # Convert to datetime
    listing_data['last_review'] = pd.to_datetime(listing_data['last_review'], errors='coerce')
    listing_data['last_scraped'] = pd.to_datetime(listing_data['last_scraped'], errors='coerce')

    # Days since last review
    listing_data['days_since_last_review'] = (listing_data['last_scraped'] - listing_data['last_review']).dt.days

    bad = listing_data['days_since_last_review'] < 0
    if bad.any():
        print("  Warning: found", int(bad.sum()), "listings with negative days. Setting to 0.")
        listing_data.loc[bad, 'days_since_last_review'] = 0

    ds = listing_data['days_since_last_review'].dropna()

# Price per person [Drop so no data leackage!!!]
if 'price' in listing_data.columns and 'accommodates' in listing_data.columns:

    # Checks
    listing_data['price'] = pd.to_numeric(listing_data['price'], errors='coerce')

    # Avoid divide-by-zero
    zero_acc = (listing_data['accommodates'] == 0).sum()
    if zero_acc > 0:
        print("  Warning: found", int(zero_acc), "listings with 0 accommodates. Setting to 1.")
        listing_data.loc[listing_data['accommodates'] == 0, 'accommodates'] = 1

    # Compute
    listing_data['price_per_person'] = listing_data['price'] / listing_data['accommodates']
    ppp = listing_data['price_per_person'].dropna()

# People per bedroom ratio
if all(col in listing_data.columns for col in ['bedrooms', 'accommodates']):

    # Handle zero bedrooms
    zero_bedrooms = (listing_data['bedrooms'] == 0).sum()

    listing_data['people_per_bedroom'] = listing_data['accommodates'] / np.maximum(listing_data['bedrooms'], 1)

    valid_ratios = listing_data['people_per_bedroom'].dropna()

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Picture URL Processing"""

# Commented out IPython magic to ensure Python compatibility.
# %%javascript
# function ClickConnect(){
#     console.log("Keeping Colab alive...");
#     document.querySelector("colab-toolbar-button#connect").click()
# }
# setInterval(ClickConnect, 60000)

# =============================================================================
# ResNet50 Feature Extraction — WITH CHECKPOINTING + PROGRESS BAR
# If Colab crashes, re-run this cell and it will resume from where it left off
# =============================================================================

import os
import gc
import numpy as np
import pandas as pd
import torch
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
from io import BytesIO
import requests as req
from sklearn.decomposition import PCA
from tqdm.notebook import tqdm
import joblib

CHECKPOINT_FEATURES = 'resnet_features_checkpoint.npy'
CHECKPOINT_FLAGS    = 'resnet_flags_checkpoint.npy'
CHECKPOINT_IDX      = 'resnet_checkpoint_idx.npy'

# ── Load checkpoint if one exists ─────────────────────────────────────────────
if (os.path.exists(CHECKPOINT_FEATURES) and
    os.path.exists(CHECKPOINT_FLAGS) and
    os.path.exists(CHECKPOINT_IDX)):

    raw_image_features = np.load(CHECKPOINT_FEATURES, allow_pickle=True).tolist()
    has_picture_flags  = np.load(CHECKPOINT_FLAGS,    allow_pickle=True).tolist()
    start_idx          = int(np.load(CHECKPOINT_IDX))
    print(f"✅ Checkpoint found — resuming from row {start_idx} of {len(listing_data)}")

else:
    raw_image_features = []
    has_picture_flags  = []
    start_idx          = 0
    print(f"No checkpoint found — starting from row 0")

# ── ResNet50 setup ─────────────────────────────────────────────────────────────
resnet = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
resnet = torch.nn.Sequential(*list(resnet.children())[:-1])
resnet.eval()

img_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

def extract_resnet_features(url):
    if pd.isna(url):
        return np.zeros(2048), False
    try:
        response = req.get(str(url), timeout=8,
                           headers={'User-Agent': 'Mozilla/5.0'})
        if response.status_code != 200:
            return np.zeros(2048), False
        img = Image.open(BytesIO(response.content)).convert('RGB')
        tensor = img_transform(img).unsqueeze(0)
        with torch.no_grad():
            features = resnet(tensor)
        return features.squeeze().numpy(), True
    except Exception:
        return np.zeros(2048), False

# ── Main extraction loop with checkpointing + progress bar ────────────────────
urls  = listing_data['picture_url'].iloc[start_idx:].tolist()
total = len(listing_data)

print(f"Extracting ResNet50 features — {total - start_idx} rows remaining...\n")

progress_bar = tqdm(
    urls,
    total=len(urls),
    desc="ResNet50 extraction",
    unit="img",
    colour="green",
    bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}]"
)

for i, url in enumerate(progress_bar):
    actual_idx = start_idx + i

    feat, flag = extract_resnet_features(url)
    raw_image_features.append(feat)
    has_picture_flags.append(int(flag))

    # Update progress bar description with running coverage %
    successes = sum(has_picture_flags)
    coverage  = successes / len(has_picture_flags) * 100
    progress_bar.set_postfix({
        "coverage": f"{coverage:.1f}%",
        "success":  successes,
        "failed":   len(has_picture_flags) - successes
    })

    # Save checkpoint every 300 rows
    if (i + 1) % 300 == 0:
        np.save(CHECKPOINT_FEATURES, np.array(raw_image_features))
        np.save(CHECKPOINT_FLAGS,    np.array(has_picture_flags))
        np.save(CHECKPOINT_IDX,      np.array(actual_idx + 1))
        gc.collect()
        tqdm.write(f"  💾 Checkpoint saved — {actual_idx + 1}/{total} rows ({(actual_idx + 1) / total * 100:.1f}%)")

progress_bar.close()

# Final checkpoint save
np.save(CHECKPOINT_FEATURES, np.array(raw_image_features))
np.save(CHECKPOINT_FLAGS,    np.array(has_picture_flags))
np.save(CHECKPOINT_IDX,      np.array(total))
print(f"\n✅ Extraction complete — {total} rows processed")

# ── PCA reduction ──────────────────────────────────────────────────────────────
listing_data['has_picture'] = has_picture_flags
img_coverage = listing_data['has_picture'].mean()
print(f"Image coverage: {img_coverage:.1%} of listings successfully processed")

print("\nRunning PCA reduction (2048 → 32 dimensions)...")
pca_img   = PCA(n_components=32, random_state=42)
image_pca = pca_img.fit_transform(np.array(raw_image_features))

for i in range(32):
    listing_data[f'img_resnet_{i}'] = image_pca[:, i]

joblib.dump(pca_img, 'pca_image.pkl')

print(f"✅ Added 32 ResNet50 PCA features (img_resnet_0 ... img_resnet_31)")
print(f"   Explained variance retained: {pca_img.explained_variance_ratio_.sum():.1%}")

# ── Clean up checkpoint files once fully done ──────────────────────────────────
for f in [CHECKPOINT_FEATURES, CHECKPOINT_FLAGS, CHECKPOINT_IDX]:
    if os.path.exists(f):
        os.remove(f)
print("\n🧹 Checkpoint files cleaned up — you're done!")

print(listing_data.shape[0])

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Amentities Processing"""

def parse_amenities(amenities_str):
    """Parse amenities string into list"""
    if pd.isna(amenities_str):
        return []

    amenities_str = str(amenities_str).strip()
    if not amenities_str or amenities_str.lower() in ['nan', 'none', '']:
        return []

    # Handle list format
    if amenities_str.startswith('[') and amenities_str.endswith(']'):
        amenities_str = amenities_str[1:-1]  # Remove brackets

    # Split by comma
    items = []
    for item in amenities_str.split(','):
        # Remove quotes and whitespace
        clean_item = item.strip().strip('"\'').strip()
        if clean_item:
            items.append(clean_item)

    return items

def has_amenity_flexible(amenities_list, amenity_terms):
    """Check for amenity with flexible matching"""
    if not amenities_list:
        return False

    amenities_lower = [item.lower() for item in amenities_list]
    amenities_text = ' '.join(amenities_lower)

    # Check if any term matches
    for term in amenity_terms:
        term_lower = term.lower()
        if any(term_lower in amenity_lower for amenity_lower in amenities_lower):
            return True
        if term_lower in amenities_text:
            return True

    return False

# Parse amenities
listing_data['amenities_list'] = listing_data['amenities'].apply(parse_amenities)
listing_data['amenities_count'] = listing_data['amenities_list'].apply(len)

# Check sample of parsed amenities
sample_amenities = listing_data['amenities_list'].iloc[0]
print(f"Sample parsed amenities (first 10): {sample_amenities[:10]}")

#Amenity Categories

# Basic Amenities
basic_amenities = {
    'wifi': ['wifi', 'wi-fi', 'wireless internet', 'internet'],
    'kitchen': ['kitchen', 'kitchenette', 'full kitchen'],
    'air_conditioning': ['air conditioning', 'ac', 'air con', 'cooling'],
    'heating': ['heating', 'heater', 'central heating', 'radiator'],
    'tv': ['tv', 'television', 'cable tv', 'smart tv', 'netflix'],
    'washer': ['washer', 'washing machine', 'laundry'],
    'dryer': ['dryer', 'tumble dryer', 'drying machine'],
    'iron': ['iron', 'ironing board'],
    'hair_dryer': ['hair dryer', 'hairdryer', 'blow dryer'],
    'essentials': ['essentials', 'basics', 'towels', 'bed sheets', 'soap', 'toilet paper']
}

# Safety Features
safety_amenities = {
    'smoke_alarm': ['smoke alarm', 'smoke detector', 'fire alarm'],
    'carbon_monoxide_alarm': ['carbon monoxide alarm', 'co detector', 'carbon monoxide detector'],
    'first_aid_kit': ['first aid kit', 'medical kit'],
    'fire_extinguisher': ['fire extinguisher'],
    'security_cameras': ['security cameras', 'surveillance', 'cctv'],
    'lockbox': ['lockbox', 'key safe', 'lock box'],
    'private_entrance': ['private entrance', 'separate entrance', 'own entrance']
}

# Kitchen & Dining
kitchen_dining = {
    'refrigerator': ['refrigerator', 'fridge', 'mini fridge', 'mini-fridge'],
    'microwave': ['microwave', 'micro wave'],
    'oven': ['oven', 'stove', 'cooktop', 'hob'],
    'dishwasher': ['dishwasher', 'dish washer'],
    'coffee_maker': ['coffee maker', 'coffee machine', 'espresso machine', 'nespresso'],
    'dining_table': ['dining table', 'dining area', 'eating area'],
    'cookware': ['cooking basics', 'pots and pans', 'cookware', 'dishes and silverware'],
    'blender': ['blender', 'food processor'],
    'toaster': ['toaster'],
    'kettle': ['kettle', 'electric kettle']
}

# Bathroom Amenities
bathroom_amenities = {
    'shampoo': ['shampoo', 'body soap', 'shower gel'],
    'conditioner': ['conditioner'],
    'body_soap': ['body soap', 'soap', 'shower gel'],
    'hot_water': ['hot water', 'hot shower'],
    'bathtub': ['bathtub', 'bath tub', 'bath'],
    'bidet': ['bidet'],
    'bathroom_essentials': ['bathroom essentials', 'bath towels', 'toilet paper']
}

# Bedroom & Living Space
bedroom_living = {
    'bed_linens': ['bed linens', 'bedding', 'sheets', 'pillows'],
    'extra_pillows': ['extra pillows', 'pillows and blankets'],
    'hangers': ['hangers', 'coat hangers', 'wardrobe'],
    'closet': ['closet', 'wardrobe', 'clothing storage'],
    'desk': ['desk', 'workspace', 'laptop friendly workspace'],
    'chair': ['chair', 'office chair', 'desk chair'],
    'sofa': ['sofa', 'couch', 'living room'],
    'blackout_curtains': ['blackout curtains', 'room darkening shades']
}

# Internet & Office
internet_office = {
    'dedicated_workspace': ['dedicated workspace', 'office space', 'work area'],
    'laptop_friendly': ['laptop friendly', 'laptop workspace'],
    'ethernet': ['ethernet connection', 'wired internet'],
    'printer': ['printer'],
    'monitor': ['monitor', 'external monitor']
}

# Entertainment
entertainment = {
    'sound_system': ['sound system', 'speakers', 'stereo'],
    'game_console': ['game console', 'playstation', 'xbox', 'nintendo'],
    'books': ['books', 'reading material'],
    'board_games': ['board games', 'card games', 'games'],
    'music': ['music', 'spotify', 'streaming']
}

# Outdoor & Recreation
outdoor_recreation = {
    'balcony': ['balcony', 'terrace', 'patio'],
    'garden': ['garden', 'yard', 'outdoor space'],
    'bbq_grill': ['bbq grill', 'barbecue', 'grill', 'outdoor grill'],
    'outdoor_furniture': ['outdoor furniture', 'patio furniture', 'garden furniture'],
    'beach_access': ['beach access', 'beachfront', 'waterfront'],
    'mountain_view': ['mountain view', 'mountains'],
    'city_view': ['city view', 'skyline view'],
    'garden_view': ['garden view', 'park view']
}

# Luxury & Premium
luxury_amenities = {
    'pool': ['pool', 'swimming pool', 'shared pool', 'private pool'],
    'hot_tub': ['hot tub', 'jacuzzi', 'spa'],
    'gym': ['gym', 'fitness centre', 'exercise equipment', 'weights'],
    'sauna': ['sauna', 'steam room'],
    'concierge': ['concierge', 'doorman', 'reception'],
    'room_service': ['room service', 'housekeeping'],
    'luxury_toiletries': ['luxury toiletries', 'premium amenities'],
    'wine_cooler': ['wine cooler', 'wine fridge', 'mini bar']
}

# Transportation & Location
transport_location = {
    'free_parking': ['free parking', 'parking included', 'garage'],
    'paid_parking': ['paid parking', 'parking available'],
    'ev_charger': ['ev charger', 'electric vehicle charging', 'tesla charger'],
    'public_transport': ['near public transport', 'metro', 'subway access'],
    'bicycle': ['bicycle', 'bike', 'cycling'],
    'airport_shuttle': ['airport shuttle', 'transfer service']
}

# Family & Accessibility
family_accessibility = {
    'family_friendly': ['family friendly', 'child friendly', 'kids welcome'],
    'crib': ['crib', 'baby cot', 'cot'],
    'high_chair': ['high chair', 'baby chair'],
    'baby_bath': ['baby bath', 'bathtub for babies'],
    'step_free_access': ['step free access', 'wheelchair accessible', 'accessible'],
    'wide_doorways': ['wide doorways', 'accessible doorways'],
    'accessible_bathroom': ['accessible bathroom', 'roll-in shower']
}

# Pets
pet_amenities = {
    'pets_allowed': ['pets allowed', 'pet friendly', 'dogs allowed', 'cats allowed'],
    'pet_bowls': ['pet bowls', 'dog bowls'],
    'pet_bed': ['pet bed', 'dog bed']
}

# Climate & Environment
climate_environment = {
    'fan': ['fan', 'ceiling fan', 'portable fan'],
    'fireplace': ['fireplace', 'wood burning fireplace'],
    'humidifier': ['humidifier'],
    'air_purifier': ['air purifier', 'hepa filter'],
    'mosquito_net': ['mosquito net', 'bug net']
}

# Combine all amenity categories
all_amenity_categories = {
    'Basic': basic_amenities,
    'Safety': safety_amenities,
    'Kitchen_Dining': kitchen_dining,
    'Bathroom': bathroom_amenities,
    'Bedroom_Living': bedroom_living,
    'Internet_Office': internet_office,
    'Entertainment': entertainment,
    'Outdoor_Recreation': outdoor_recreation,
    'Luxury': luxury_amenities,
    'Transport_Location': transport_location,
    'Family_Accessibility': family_accessibility,
    'Pet': pet_amenities,
    'Climate_Environment': climate_environment
}

# Create binary features for all amenities
amenity_feature_count = 0

for category_name, category_amenities in all_amenity_categories.items():
    category_count = 0
    for amenity, search_terms in category_amenities.items():
        col_name = f"has_{amenity}"
        listing_data[col_name] = listing_data['amenities_list'].apply(
            lambda x: has_amenity_flexible(x, search_terms)
        )
        amenity_feature_count += 1
        category_count += 1

print(f"Total amenity features created: {amenity_feature_count}")

# Create category counts
for category_name, category_amenities in all_amenity_categories.items():
    category_cols = [f"has_{amenity}" for amenity in category_amenities.keys()]
    existing_cols = [col for col in category_cols if col in listing_data.columns]

    count_col = f"{category_name.lower()}_amenities_count"
    listing_data[count_col] = listing_data[existing_cols].sum(axis=1)

# Create overall amenity quality scores

# Basic necessity score
basic_essentials = ['has_wifi', 'has_kitchen', 'has_tv', 'has_essentials', 'has_heating']
existing_basic = [col for col in basic_essentials if col in listing_data.columns]
listing_data['basic_amenities_score'] = listing_data[existing_basic].sum(axis=1)

# Luxury score
luxury_features = ['has_pool', 'has_hot_tub', 'has_gym', 'has_concierge', 'has_room_service']
existing_luxury = [col for col in luxury_features if col in listing_data.columns]
listing_data['luxury_amenities_score'] = listing_data[existing_luxury].sum(axis=1)

# Convenience score
convenience_features = ['has_washer', 'has_dryer', 'has_dishwasher', 'has_free_parking', 'has_elevator']
existing_convenience = [col for col in convenience_features if col in listing_data.columns]
listing_data['convenience_amenities_score'] = listing_data[existing_convenience].sum(axis=1)

print(f"Basic amenities score range: {listing_data['basic_amenities_score'].min()} - {listing_data['basic_amenities_score'].max()}")
print(f"Luxury amenities score range: {listing_data['luxury_amenities_score'].min()} - {listing_data['luxury_amenities_score'].max()}")
print(f"Convenience amenities score range: {listing_data['convenience_amenities_score'].min()} - {listing_data['convenience_amenities_score'].max()}")

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Text Feature Engineering"""

# Enhanced Name Features
def extract_name_features(name):
    """Extract comprehensive features from listing name"""
    if pd.isna(name):
        return {
            'name_length': 0, 'name_word_count': 0, 'name_luxury_score': 0,
            'name_location_score': 0, 'name_mentions_apartment': False,
            'name_mentions_house': False, 'name_mentions_studio': False,
            'name_mentions_loft': False, 'name_mentions_room': False,
            'name_comfort_score': 0, 'name_mentions_private': False,
            'name_mentions_entire': False, 'name_view_score': 0,
            'name_mentions_central': False, 'name_mentions_modern': False
        }

    name_lower = str(name).lower()
    features = {}

    # Basic text statistics
    features['name_length'] = len(name)
    features['name_word_count'] = len(name.split())

    # Luxury indicators
    luxury_words = ['luxury', 'luxurious', 'premium', 'deluxe', 'executive',
                   'penthouse', 'villa', 'mansion', 'suite', 'presidential']
    features['name_luxury_score'] = sum(1 for word in luxury_words if word in name_lower)

    # Location indicators
    location_words = ['central', 'centre', 'center', 'downtown', 'city centre',
                     'city center', 'heart of', 'near', 'close to', 'walking distance',
                     'zone 1', 'zone 2', 'prime location']
    features['name_location_score'] = sum(1 for word in location_words if word in name_lower)

    # Property type indicators
    features['name_mentions_apartment'] = any(word in name_lower for word in ['apartment', 'flat', 'apt'])
    features['name_mentions_house'] = any(word in name_lower for word in ['house', 'home', 'cottage', 'townhouse'])
    features['name_mentions_studio'] = 'studio' in name_lower
    features['name_mentions_loft'] = 'loft' in name_lower
    features['name_mentions_room'] = 'room' in name_lower and 'bedroom' not in name_lower

    # Comfort and quality indicators
    comfort_words = ['cosy', 'cozy', 'comfortable', 'spacious', 'bright', 'modern',
                    'stylish', 'beautiful', 'charming', 'elegant', 'sophisticated']
    features['name_comfort_score'] = sum(1 for word in comfort_words if word in name_lower)

    # Privacy indicators
    features['name_mentions_private'] = 'private' in name_lower
    features['name_mentions_entire'] = any(word in name_lower for word in ['entire', 'whole', 'full'])

    # View indicators
    view_words = ['view', 'garden', 'balcony', 'terrace', 'sea view', 'ocean view',
                 'mountain view', 'city view', 'river view', 'park view', 'skyline']
    features['name_view_score'] = sum(1 for word in view_words if word in name_lower)

    # Specific location features
    features['name_mentions_central'] = any(word in name_lower for word in ['central', 'centre', 'center'])
    features['name_mentions_modern'] = any(word in name_lower for word in ['modern', 'contemporary', 'new', 'renovated'])

    return features

name_features = listing_data['name'].apply(extract_name_features)
name_features_df = pd.json_normalize(name_features)
name_features_df.index = listing_data.index

# Add name features to main dataframe
for col in name_features_df.columns:
    listing_data[col] = name_features_df[col]

print(f"Name features created: {len(name_features_df.columns)}")

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

# Enhanced Description Processing
def calculate_readability_score(text):
    """Calculate readability score using Flesch formula"""
    if pd.isna(text) or len(str(text).strip()) == 0:
        return 0

    text_str = str(text)
    sentences = len([s for s in text_str.split('.') if s.strip()])
    words = len(text_str.split())

    if sentences == 0 or words == 0:
        return 0

    # Count syllables
    vowels = 'aeiouAEIOU'
    syllables = sum(1 for char in text_str if char in vowels)

    if syllables == 0:
        syllables = words  # Fallback

    # Reading Ease formula
    avg_sentence_length = words / sentences
    avg_syllables_per_word = syllables / words

    readability = 206.835 - (1.015 * avg_sentence_length) - (84.6 * avg_syllables_per_word)
    return max(0, min(100, readability))

def calculate_sentiment_score(text):
    """Calculate sentiment"""
    if pd.isna(text):
        return 0

    text_lower = str(text).lower()

    # Positive words
    positive_words = [
        'amazing', 'beautiful', 'perfect', 'excellent', 'wonderful', 'fantastic',
        'great', 'awesome', 'lovely', 'stunning', 'spectacular', 'incredible',
        'comfortable', 'cosy', 'cozy', 'charming', 'peaceful', 'relaxing',
        'enjoyable', 'delightful', 'convenient', 'spacious', 'bright', 'clean',
        'modern', 'stylish', 'elegant', 'sophisticated', 'luxury', 'premium',
        'superb', 'outstanding', 'exceptional', 'brilliant', 'magnificent',
        'gorgeous', 'fabulous', 'splendid', 'marvellous', 'marvelous'
    ]

    # Negative words
    negative_words = [
        'terrible', 'awful', 'bad', 'horrible', 'disappointing', 'dirty',
        'noisy', 'uncomfortable', 'small', 'cramped', 'old', 'outdated',
        'inconvenient', 'difficult', 'problems', 'issues', 'broken',
        'poor', 'worst', 'unpleasant', 'disgusting', 'nasty', 'dreadful'
    ]

    positive_count = sum(1 for word in positive_words if word in text_lower)
    negative_count = sum(1 for word in negative_words if word in text_lower)

    # Calculate sentiment score
    total_words = len(text_lower.split())
    if total_words == 0:
        return 0

    sentiment_score = (positive_count - negative_count) / max(total_words / 20, 1)
    return max(-1, min(1, sentiment_score))

def extract_description_features(description):
    """Extract features from description"""
    if pd.isna(description):
        return {
            'desc_length': 0, 'desc_word_count': 0, 'desc_sentence_count': 0,
            'avg_word_length': 0, 'desc_readability': 0, 'desc_sentiment_score': 0,
            'desc_luxury_mentions': 0, 'desc_location_mentions': 0, 'desc_transport_mentions': 0,
            'desc_experience_mentions': 0, 'desc_facility_mentions': 0, 'desc_business_mentions': 0,
            'desc_safety_mentions': 0, 'desc_cleanliness_mentions': 0, 'desc_comfort_mentions': 0,
            'desc_view_mentions': 0, 'desc_activity_mentions': 0, 'desc_food_mentions': 0,
            'desc_family_mentions': 0, 'desc_romantic_mentions': 0, 'desc_exclamation_count': 0,
            'desc_question_count': 0, 'desc_caps_ratio': 0, 'desc_number_count': 0
        }

    desc_str = str(description)
    desc_lower = desc_str.lower()
    words = desc_str.split()

    features = {}

    # Basic text statistics
    features['desc_length'] = len(desc_str)
    features['desc_word_count'] = len(words)
    features['desc_sentence_count'] = len([s for s in desc_str.split('.') if s.strip()])
    features['avg_word_length'] = np.mean([len(word) for word in words]) if words else 0

    # Readability and sentiment
    features['desc_readability'] = calculate_readability_score(desc_str)
    features['desc_sentiment_score'] = calculate_sentiment_score(desc_str)

    # Theme-based mentions
    luxury_words = ['luxury', 'luxurious', 'premium', 'upscale', 'high-end', 'exclusive', 'elegant']
    features['desc_luxury_mentions'] = sum(1 for word in luxury_words if word in desc_lower)

    location_words = ['location', 'neighbourhood', 'neighborhood', 'area', 'district', 'zone',
                     'close', 'near', 'walking', 'minutes', 'central', 'convenient']
    features['desc_location_mentions'] = sum(1 for word in location_words if word in desc_lower)

    transport_words = ['metro', 'tube', 'underground', 'subway', 'bus', 'train', 'station',
                      'transport', 'uber', 'taxi', 'airport', 'railway']
    features['desc_transport_mentions'] = sum(1 for word in transport_words if word in desc_lower)

    experience_words = ['experience', 'enjoy', 'relax', 'explore', 'discover', 'adventure',
                       'stay', 'visit', 'holiday', 'vacation', 'getaway']
    features['desc_experience_mentions'] = sum(1 for word in experience_words if word in desc_lower)

    facility_words = ['kitchen', 'bathroom', 'bedroom', 'living', 'dining', 'balcony',
                     'garden', 'parking', 'wifi', 'pool', 'gym']
    features['desc_facility_mentions'] = sum(1 for word in facility_words if word in desc_lower)

    business_words = ['business', 'work', 'workspace', 'office', 'meetings', 'conference',
                     'professional', 'corporate']
    features['desc_business_mentions'] = sum(1 for word in business_words if word in desc_lower)

    safety_words = ['safe', 'secure', 'security', 'safety', 'protected', 'gated', 'keyless']
    features['desc_safety_mentions'] = sum(1 for word in safety_words if word in desc_lower)

    cleanliness_words = ['clean', 'fresh', 'spotless', 'sanitised', 'sanitized', 'hygienic', 'tidy']
    features['desc_cleanliness_mentions'] = sum(1 for word in cleanliness_words if word in desc_lower)

    comfort_words = ['comfortable', 'cosy', 'cozy', 'relaxing', 'peaceful', 'quiet', 'serene']
    features['desc_comfort_mentions'] = sum(1 for word in comfort_words if word in desc_lower)

    view_words = ['view', 'views', 'overlook', 'facing', 'panoramic', 'scenic']
    features['desc_view_mentions'] = sum(1 for word in view_words if word in desc_lower)

    activity_words = ['restaurant', 'shopping', 'museum', 'theatre', 'theater', 'park', 'beach',
                     'nightlife', 'entertainment', 'attractions']
    features['desc_activity_mentions'] = sum(1 for word in activity_words if word in desc_lower)

    food_words = ['restaurant', 'food', 'dining', 'cafe', 'coffee', 'breakfast', 'kitchen']
    features['desc_food_mentions'] = sum(1 for word in food_words if word in desc_lower)

    family_words = ['family', 'children', 'kids', 'child-friendly', 'family-friendly']
    features['desc_family_mentions'] = sum(1 for word in family_words if word in desc_lower)

    romantic_words = ['romantic', 'couple', 'honeymoon', 'intimate', 'private']
    features['desc_romantic_mentions'] = sum(1 for word in romantic_words if word in desc_lower)

    # Punctuation and formatting features
    features['desc_exclamation_count'] = desc_str.count('!')
    features['desc_question_count'] = desc_str.count('?')

    # Capital letters ratio
    caps_count = sum(1 for char in desc_str if char.isupper())
    features['desc_caps_ratio'] = caps_count / len(desc_str) if len(desc_str) > 0 else 0

    # Number count
    features['desc_number_count'] = sum(1 for word in words if any(char.isdigit() for char in word))

    return features

if 'description' in listing_data.columns:
    desc_features = listing_data['description'].apply(extract_description_features)
    desc_features_df = pd.json_normalize(desc_features)
    desc_features_df.index = listing_data.index

    # Add description features to main dataframe
    for col in desc_features_df.columns:
        listing_data[col] = desc_features_df[col]

    print(f"Description features created: {len(desc_features_df.columns)}")

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

# --- BERT Embeddings for Name and Description ---
from tqdm import tqdm
from sklearn.decomposition import PCA
import joblib
import numpy as np

tqdm.pandas()

print("Loading DistilBERT tokenizer and model...")
from transformers import DistilBertTokenizer, DistilBertModel
import torch

bert_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
bert_model = DistilBertModel.from_pretrained('distilbert-base-uncased')
bert_model.eval()

def get_bert_embedding(text, max_length=128):
    """Return 768-dim CLS embedding for a piece of text."""
    if pd.isna(text) or str(text).strip() == '':
        return np.zeros(768)
    inputs = bert_tokenizer(
        str(text),
        return_tensors='pt',
        max_length=max_length,
        truncation=True,
        padding='max_length'
    )
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()

# --- Name embeddings ---
print("Generating BERT embeddings for listing names...")
name_embeddings = np.vstack(
    listing_data['name'].progress_apply(get_bert_embedding).values
)

# --- Description embeddings ---
print("Generating BERT embeddings for descriptions...")
desc_embeddings = np.vstack(
    listing_data['description'].fillna('').progress_apply(
        lambda t: get_bert_embedding(t, max_length=256)
    ).values
)

print(f"Name embedding shape: {name_embeddings.shape}")
print(f"Desc embedding shape: {desc_embeddings.shape}")

# PCA: 768 -> 32 dimensions each
pca_name_bert = PCA(n_components=32, random_state=42)
name_bert_pca = pca_name_bert.fit_transform(name_embeddings)

pca_desc_bert = PCA(n_components=32, random_state=42)
desc_bert_pca = pca_desc_bert.fit_transform(desc_embeddings)

for i in range(32):
    listing_data[f'name_bert_{i}'] = name_bert_pca[:, i]
    listing_data[f'desc_bert_{i}'] = desc_bert_pca[:, i]

# Save PCA objects for Streamlit app
joblib.dump(pca_name_bert, 'pca_name_bert.pkl')
joblib.dump(pca_desc_bert, 'pca_desc_bert.pkl')

bert_tokenizer.save_pretrained('distilbert_tokenizer')
bert_model.save_pretrained('distilbert_model')

print(f"\nAdded 64 BERT-derived features (32 name + 32 description)")
print(f"Name embedding variance retained: {pca_name_bert.explained_variance_ratio_.sum():.1%}")
print(f"Desc embedding variance retained: {pca_desc_bert.explained_variance_ratio_.sum():.1%}")

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

# Create Overall Text Quality Score
def calculate_overall_text_quality(row):
    """Calculate comprehensive text quality score"""
    score = 0

    # Name contribution (25% weight)
    name_score = (
        row.get('name_luxury_score', 0) * 3 +
        row.get('name_location_score', 0) * 2 +
        row.get('name_comfort_score', 0) * 2 +
        row.get('name_view_score', 0) * 1.5 +
        (2 if row.get('name_mentions_private', False) else 0) +
        (1.5 if row.get('name_mentions_entire', False) else 0)
    )
    score += name_score * 0.25

    # Description contribution (50% weight)
    desc_score = (
        row.get('desc_luxury_mentions', 0) * 3 +
        row.get('desc_experience_mentions', 0) * 2 +
        row.get('desc_cleanliness_mentions', 0) * 2.5 +
        row.get('desc_safety_mentions', 0) * 2 +
        row.get('desc_comfort_mentions', 0) * 2 +
        (row.get('desc_sentiment_score', 0) + 1) * 5 +  # Normalise sentiment (-1 to 1) to (0 to 2)
        row.get('desc_facility_mentions', 0) * 1.5 +
        row.get('desc_location_mentions', 0) * 1.5
    )
    score += desc_score * 0.5

    # Amenities contribution (25% weight)
    amenities_score = (
        row.get('luxury_amenities_score', 0) * 4 +
        row.get('convenience_amenities_score', 0) * 2.5 +
        row.get('basic_amenities_score', 0) * 2 +
        row.get('safety_amenities_count', 0) * 2
    )
    score += amenities_score * 0.25

    return score

listing_data['overall_text_quality'] = listing_data.apply(calculate_overall_text_quality, axis=1)

# Create percentile rankings
listing_data['text_quality_percentile'] = listing_data['overall_text_quality'].rank(pct=True) * 100

# Create categorical quality levels
def categorise_quality(percentile):
    if percentile >= 95:
        return 'Exceptional'
    elif percentile >= 85:
        return 'Premium'
    elif percentile >= 70:
        return 'High'
    elif percentile >= 50:
        return 'Good'
    elif percentile >= 30:
        return 'Average'
    else:
        return 'Basic'

listing_data['text_quality_category'] = listing_data['text_quality_percentile'].apply(categorise_quality)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Handling Outliers"""

def handle_outliers_iqr(df, column, method='clip'):
    """Handle outliers using IQR method"""
    if column not in df.columns:
        print(f"Column {column} not found")
        return df

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers_count = ((df[column] < lower_bound) | (df[column] > upper_bound)).sum()

    if method == 'clip':
        df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)
        print(f"{column}: Clipped {outliers_count} outliers (bounds: {lower_bound:.2f} - {upper_bound:.2f})")

    return df

# Use percentile method for price
if 'price' in listing_data.columns:
    print("Handling price outliers...")
    price_before = listing_data['price'].describe()

    lower_bound = listing_data['price'].quantile(0.005)  # 0.5th percentile
    upper_bound = listing_data['price'].quantile(0.995)  # 99.5th percentile

    outliers_count = ((listing_data['price'] < lower_bound) | (listing_data['price'] > upper_bound)).sum()
    listing_data['price'] = listing_data['price'].clip(lower=lower_bound, upper=upper_bound)

    print(f"Price: Clipped {outliers_count} outliers (bounds: £{lower_bound:.2f} - £{upper_bound:.2f})")
    print("Price distribution after outlier handling:")
    print(listing_data['price'].describe())

# Handle other numeric outliers
numeric_outlier_cols = ['accommodates', 'bedrooms', 'beds', 'bathrooms', 'number_of_reviews']
for col in numeric_outlier_cols:
    if col in listing_data.columns:
        listing_data = handle_outliers_iqr(listing_data, col, method='clip')

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Encode Categorical Variables"""

# Ordinal encoding for host response time
if 'host_response_time' in listing_data.columns:
    response_time_order = ['within an hour', 'within a few hours', 'within a day',
                          'a few days or more', 'unknown']
    response_time_map = {v: i for i, v in enumerate(response_time_order)}
    listing_data['host_response_time_encoded'] = listing_data['host_response_time'].map(response_time_map)

    for k, v in response_time_map.items():
        count = (listing_data['host_response_time'] == k).sum()
        print(f"  {k}: {v} ({count} listings)")

# Check cardinality of categorical variables before encoding
categorical_for_encoding = ['property_type', 'room_type', 'neighbourhood_cleansed',
                           'neighbourhood_group_cleansed', 'text_quality_category']

for col in categorical_for_encoding:
    if col in listing_data.columns:
        unique_count = listing_data[col].nunique()
        print(f"{col}: {unique_count} unique values")

        # Show top categories
        top_cats = listing_data[col].value_counts().head()
        print(f"  Top categories: {top_cats.to_dict()}")

# One-hot encoding but limit to top categories
def prepare_categorical_for_encoding(df, column, max_categories=20):
    """Prepare categorical column for encoding by limiting to top categories"""
    if column not in df.columns:
        return df

    value_counts = df[column].value_counts()

    if len(value_counts) > max_categories:
        top_categories = value_counts.head(max_categories).index.tolist()
        df[f"{column}_grouped"] = df[column].apply(
            lambda x: x if x in top_categories else 'Other'
        )
        print(f"{column}: Grouped to top {max_categories} categories + 'Other'")
        return f"{column}_grouped"
    else:
        return column

# Prepare high-cardinality categorical variables
prepared_categoricals = []
for col in categorical_for_encoding:
    if col in listing_data.columns:
        prepared_col = prepare_categorical_for_encoding(listing_data, col, max_categories=15)
        prepared_categoricals.append(prepared_col)

# One-hot encode categorical variables
categorical_columns = ['room_type', 'property_type_grouped', 'text_quality_category']
listing_data = pd.get_dummies(listing_data, columns=categorical_columns, prefix=categorical_columns)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

"""### Final Preparations"""

# Remove columns that won't be useful for modelling
final_drop_cols = [
    'last_scraped', 'host_since', 'calendar_last_scraped', 'first_review', 'last_review',
    'description', 'name', 'amenities', 'host_verifications', 'neighborhood_overview',
    'amenities_list', 'host_response_time', 'host_id', 'host_name', 'host_listinga_count',
    'source', 'id',
    'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm',
    'maximum_nights_avg_ntm', 'has_availability', 'availability_30', 'availability_60',
    'availability_90', 'availability_365', 'number_of_reviews_ltm', 'number_of_reviews_l300d',
    'availability_eoy', 'number_of_reviews_ly', 'host_listings_count', 'neighbourhood_cleansed',
    'bathrooms_text', 'number_of_reviews_l30d', 'estimated_occupancy_l365d', 'estimated_revenue_l365d',
    'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes',
    'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms',
    'property_type', 'neighbourhood_group_cleansed', 'picture_url', 'price_per_person'
]

existing_final_drops = [col for col in final_drop_cols if col in listing_data.columns]
print(f"Dropping {len(existing_final_drops)} columns: {existing_final_drops}")
listing_data = listing_data.drop(columns=existing_final_drops)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

print("Final dataset shape:", listing_data.shape)

listing_data.head()

listing_data.info()

# Check for any remaining issues
remaining_missing = listing_data.isnull().sum()
cols_with_missing = remaining_missing[remaining_missing > 0]

print(cols_with_missing)

# Handle any remaining missing values
final_missing = listing_data.isnull().sum()
cols_with_final_missing = final_missing[final_missing > 0]

if len(cols_with_final_missing) > 0:

    # Drop rows with missing target variable (price)
    if 'price' in cols_with_final_missing.index:
        before_count = len(listing_data)
        listing_data = listing_data.dropna(subset=['price'])
        after_count = len(listing_data)

    # Fill remaining missing values
    for col in cols_with_final_missing.index:
        if col in listing_data.columns and col != 'price':
            if listing_data[col].dtype in ['float64', 'int64']:
                fill_value = listing_data[col].median()
            else:
                fill_value = listing_data[col].mode().iloc[0] if len(listing_data[col].mode()) > 0 else 'unknown'

            listing_data[col] = listing_data[col].fillna(fill_value)

print(f">>> CHECKPOINT: {len(listing_data)} rows remaining")

# Save processed data and all model files
listing_data.to_csv('airbnb_processed_data_multimodal.csv', index=False)

print(f"Final dataset shape: {listing_data.shape}")
print(f"Saved to airbnb_processed_data_multimodal.csv")
print("\nFiles to download:")
print("1. airbnb_processed_data_multimodal.csv")
print("2. pca_name_bert.pkl")
print("3. pca_desc_bert.pkl")
print("4. pca_image.pkl")

import shutil
shutil.make_archive('distilbert_tokenizer', 'zip', 'distilbert_tokenizer')
shutil.make_archive('distilbert_model', 'zip', 'distilbert_model')
